### ISSUE TITLE
Translate conditional requirements into JSON schema

### ISSUE THREAD

**Issue by nealkruis** [open205/schema-205#32]
Here's a [helpful post on the capabilities in JSON schema](https://stackoverflow.com/questions/38717933/jsonschema-attribute-conditionally-required).

Here are the cases to handle:

# Is defined

```yaml
a:
  Data Type: "Boolean"
  Required: True
b:
  Data Type: "Numeric"  
  Required: "if a"
c:
  Data Type: "Numeric"  
  Required: True
```

gives

```json
{
  "type": "object",
  "properties": {
    "a": { "type": "boolean" },
    "b": { "type": "number" },
    "c": { "type": "number" }
  },
  "required": ["a", "c"],
  "dependencies": {
    "a": ["b"]
  }
}
```

# Is equal

```yaml
a:
  Data Type: "Boolean"
  Required: True
b:
  Data Type: "Numeric"  
  Required: "if a=False"
c:
  Data Type: "Numeric"  
  Required: True
```

gives

```json
{
  "type": "object",
  "properties": {
    "a": { "type": "boolean" },
    "b": { "type": "number" },
    "c": { "type": "number" }
  },
  "required": ["a", "c"],
  "if": {
      "properties": {
        "a": { "const": false} 
      }
  },
  "then": { "required": ["b"] }
}
```

# Is not equal

```yaml
a:
  Data Type: "Boolean"
  Required: True
b:
  Data Type: "Numeric"  
  Required: "if a!=False"
c:
  Data Type: "Numeric"  
  Required: True
```

gives

```json
{
  "type": "object",
  "properties": {
    "a": { "type": "boolean" },
    "b": { "type": "number" },
    "c": { "type": "number" }
  },
  "required": ["a", "c"],
  "if": {
      "properties": {
        "a": { "not": {"const": false} }
      }
  },
  "then": { "required": ["b"] }
}
```

We may be able to find ways to combine these too. But I think covering these cases for now should be fine.
